Run ci on github actions
- runs unit tests
- builds kpack images via pack
- pushes the images to a dev registry & creates a prerelease
- creates a kind cluster and deploys pre-release
- runs e2e the tests on there
- if branch matches `release/x.y.z` where where x is major, y is minor,
  z is patch, the images will be promoted to release registry and final
  release is generated. Then a draft release will be created
- update the git fetcher test to be slightly less sensitive. this was
causing issues on github actions where the error is `Temporary failure
in name resolution` instead of `no such host`

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,20 +1,485 @@
-name: CI
+name: ci
 
 on:
   push:
     branches:
     - main
-  pull_request: {}
+    - release/**
+  pull_request:
+    branches:
+    - main
+    - release/**
+
+defaults:
+  run:
+    shell: bash
+
+env:
+  PUBLIC_IMAGE_DEV_REPO: gcr.io/cf-build-service-public/kpack-dev
+  PUBLIC_IMAGE_REPO: gcr.io/cf-build-service-public/kpack
+  PACK_VERSION: 0.29.0
+  CRANE_WINDOWS_VERSION: 0.14.0
 
 jobs:
-
-  test:
+  unit:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version-file: 'go.mod'
+
     - name: Run tests
-      uses: ./.github/actions/run-tests
+      run: make unit-ci
+
     - name: Report coverage
       run: bash <(curl -s https://codecov.io/bash)
       env:
-        CODECOV_TOKEN: 4e256ab5-d474-459d-8d4d-cffea6455db7
+        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+
+  build-images-windows:
+    runs-on: windows-2019
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Setup pack
+      run: |
+        url="https://github.com/buildpacks/pack/releases/download/v${{ env.PACK_VERSION }}/pack-v${{ env.PACK_VERSION }}-windows.zip"
+        curl -sSL "$url" -o pack.zip
+        unzip -o pack.zip
+
+        mkdir "${HOME}"/.pack
+        echo "experimental = true" > "${HOME}"/.pack/config.toml
+
+        ./pack version
+
+    - name: Build images
+      if: ${{ steps.cache-images-windows.outputs.cache-hit != 'true' }}
+      run: |
+        export PATH="$PATH:$(pwd)"
+
+        [[ $GITHUB_REF =~ ^refs\/heads\/release\/(.*)$ ]] && version=${BASH_REMATCH[1]} || version=0.0.0
+
+        KPACK_VERSION=$version
+        KPACK_COMMIT=$GITHUB_SHA
+
+        PACK_OPTS="--builder gcr.io/dotnet-build-gcp/go-multios/builder-windows --trust-builder"
+
+        mkdir images-windows
+
+        # usage: pack_save source tag
+        pack_save() {
+          pack build "$2" $PACK_OPTS \
+            --env BP_GO_TARGETS="$1" \
+            --env BP_GO_LDFLAGS="-X 'github.com/pivotal/kpack/cmd.Version=${KPACK_VERSION}' -X 'github.com/pivotal/kpack/cmd.Commit=${KPACK_COMMIT}'"
+          docker save $2 > "images-windows/$2.tar"
+        }
+
+        pack_save '.\cmd\completion' completion-windows
+        pack_save '.\cmd\build-init;.\cmd\network-wait-launcher' build-init-windows
+
+    - name: Upload Image Artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: images-windows
+        path: images-windows/*.tar
+
+  build-images-linux:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version-file: 'go.mod'
+
+    - name: Setup pack
+      uses: buildpacks/github-actions/setup-pack@v5.0.0
+      with:
+        pack-version: ${{ env.PACK_VERSION }}
+
+    - name: Build images
+      if: ${{ steps.cache-images-linux.outputs.cache-hit != 'true' }}
+      run: |
+        [[ $GITHUB_REF =~ ^refs\/heads\/release\/(.*)$ ]] && version=${BASH_REMATCH[1]} || version=0.0.0
+
+        KPACK_VERSION=$version
+        KPACK_COMMIT=$GITHUB_SHA
+        PACK_OPTS="--network host --builder paketobuildpacks/builder-jammy-tiny"
+
+        mkdir images-linux
+
+        # usage: pack_save source tag
+        pack_save() {
+          pack build "$2" $PACK_OPTS \
+            --env BP_GO_TARGETS="$1" \
+            --env BP_GO_LDFLAGS="-X 'github.com/pivotal/kpack/cmd.Version=${KPACK_VERSION}' -X 'github.com/pivotal/kpack/cmd.Commit=${KPACK_COMMIT}'"
+          docker save $2 > "images-linux/$2.tar"
+        }
+
+        pack_save ./cmd/controller controller
+        pack_save ./cmd/webhook webhook
+        pack_save ./cmd/build-init build-init
+        pack_save ./cmd/rebase rebase
+        pack_save ./cmd/build-waiter build-waiter
+        pack_save ./cmd/completion completion
+        
+        output=$(go run ./hack/lifecycle/main.go --tag=lifecycle --publish=false 2>&1)
+        IMAGE=$(echo "$output" | grep "saved lifecycle" | awk -F  "saved lifecycle image: " '{print $2}')
+        docker save $IMAGE > images-linux/lifecycle.tar
+
+    - name: Upload Image Artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: images-linux
+        path: images-linux/*.tar
+
+  push-images:
+    runs-on: ubuntu-latest
+    needs:
+    - build-images-linux
+    - build-images-windows
+    steps:
+    - name: Setup crane
+      uses: imjasonh/setup-crane@v0.3
+
+    - name: Setup carvel
+      uses: carvel-dev/setup-action@v1
+      with:
+        token: ${{ secrets.RELEASE_TOKEN }}
+        only: ytt, kapp
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v3
+
+    - name: Docker Login
+      uses: docker/login-action@v2.1.0
+      with:
+        registry: gcr.io
+        username: _json_key
+        password: ${{ secrets.GCR_PUBLIC_SA }}
+
+    - name: Push images
+      env:
+        gcr_token: ${{ secrets.GCR_PUBLIC_SA }}
+      run: |
+        mkdir image-refs
+        for image in **/*.tar; do
+          name=$(basename ${image%.tar})
+          crane push $image "${{ env.PUBLIC_IMAGE_DEV_REPO }}/${name}" --image-refs "image-refs/${name}"
+        done
+
+    - name: Upload image refs
+      uses: actions/upload-artifact@v3
+      with:
+        name: image-refs
+        path: image-refs/*
+
+  generate-pre-release-yaml:
+    runs-on: ubuntu-latest
+    needs:
+    - push-images
+    - build-images-linux
+    - build-images-windows
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version-file: 'go.mod'
+
+    - name: Setup carvel
+      uses: carvel-dev/setup-action@v1
+      with:
+        token: ${{ secrets.RELEASE_TOKEN }}
+        only: ytt, kapp
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v3
+      with:
+        name: image-refs
+
+    - name: Build release yaml
+      run: |        
+        ytt -f config/ \
+          -v controller_image=$(cat controller) \
+          -v webhook_image=$(cat webhook) \
+          -v build_init_image=$(cat build-init) \
+          -v build_init_windows_image=$(cat build-init-windows) \
+          -v build_waiter_image=$(cat build-waiter) \
+          -v rebase_image=$(cat rebase) \
+          -v completion_image=$(cat completion) \
+          -v completion_windows_image=$(cat completion-windows) \
+          -v lifecycle_image=$(cat lifecycle) > prerelease.yaml
+
+        cat prerelease.yaml
+
+    - name: Upload Pre-Release
+      uses: actions/upload-artifact@v3
+      with:
+        name: prerelease
+        path: prerelease.yaml
+
+  e2e:
+    needs:
+      - generate-pre-release-yaml
+      - push-images
+      - build-images-linux
+      - build-images-windows
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version-file: 'go.mod'
+
+    - name: Setup crane
+      uses: imjasonh/setup-crane@v0.3
+
+    - name: Setup carvel
+      uses: carvel-dev/setup-action@v1
+      with:
+        token: ${{ secrets.RELEASE_TOKEN }}
+        only: ytt, kapp
+
+    - name: Download release
+      uses: actions/download-artifact@v3
+      with:
+        name: prerelease
+
+    - name: Setup local registry
+      run: |
+        user="test"
+        pass="test"
+
+        echo "Generating users"
+        htpasswd -Bbn "$user" "$pass" >> htpasswd # authenticated user for tests
+
+        # the registry can be accessed from inside the kind cluster via it's name.
+        # however, due to a quirk with ggcr, it will force https connections UNLESS
+        # it fits certain patterns (https://github.com/google/go-containerregistry/blob/b8d1c0a1df12a3b3dd3e7f98330780fdc015ce40/pkg/name/registry.go#L75)
+        # so in order to avoid setting tls for the registry, we can name it something.local
+        # to trick ggcr into using the http scheme
+        name="registry.local"
+
+        echo "Starting registry"
+        if [ "$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)" != 'true' ]; then
+          docker run --detach \
+            --name "$name" \
+            -v "$(pwd)/htpasswd:/auth/htpasswd" \
+            -e "REGISTRY_AUTH=htpasswd" \
+            -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
+            -e "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd" \
+            -e "REGISTRY_STORAGE_DELETE_ENABLED=true" \
+            --publish "5000:5000" \
+            registry:2
+        fi
+
+        echo "REGISTRY_URL=$name:5000" >> $GITHUB_ENV
+        echo "REGISTRY_USER=$user" >> $GITHUB_ENV
+        echo "REGISTRY_PASS=$pass" >> $GITHUB_ENV
+
+        # alias registry.local to localhost
+        # ip=$(docker container inspect $name --format '{{ .NetworkSettings.Networks.kind.IPAddress }}')
+        ip=127.0.0.1
+        echo "$ip registry.local" | sudo tee -a /etc/hosts
+
+        cat <<EOF > kind.yaml
+        kind: Cluster
+        apiVersion: kind.x-k8s.io/v1alpha4
+        containerdConfigPatches:
+        - |-
+          [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.local:5000"]
+            endpoint = ["http://registry.local:5000"]
+        EOF
+
+    - name: Create Kind Cluster
+      uses: helm/kind-action@v1.5.0
+      with:
+        cluster_name: e2e
+        config: kind.yaml
+
+    - name: Docker Login
+      uses: docker/login-action@v2.1.0
+      with:
+        registry: ${{ env.REGISTRY_URL }}
+        username: ${{ env.REGISTRY_USER }}
+        password: ${{ env.REGISTRY_PASS }}
+
+    - name: Run tests
+      run: |        
+        # make the registry container accessible by name from inside the cluster
+        docker network connect kind registry.local
+
+        kapp deploy -a kpack -y -f prerelease.yaml
+
+        export IMAGE_REGISTRY=${{ env.REGISTRY_URL }}
+        export IMAGE_REGISTRY_USERNAME=${{ env.REGISTRY_USER }}
+        export IMAGE_REGISTRY_PASSWORD=${{ env.REGISTRY_PASS }}
+
+        make e2e
+        kapp delete -a kpack -y
+
+    - name: Run tests with Istio
+      run: |
+        helm repo add istio https://istio-release.storage.googleapis.com/charts
+        helm repo update
+        kubectl create namespace istio-system
+        helm install istio-base istio/base -n istio-system --wait
+        helm install istiod istio/istiod -n istio-system --wait    
+        
+        cat <<EOF > overlay.yaml
+        #@ load("@ytt:overlay", "overlay")
+        #@overlay/match by=overlay.subset({"metadata":{"name":"kpack-controller"}, "kind": "Deployment"})
+        ---
+        spec:
+          template:
+            spec:
+              containers:
+              #@overlay/match by="name"
+              - name: controller
+                #@overlay/match-child-defaults missing_ok=True
+                env:
+                #@overlay/match by="name"
+                #@overlay/replace or_add=True
+                - name: INJECTED_SIDECAR_SUPPORT
+                  value: "true"
+        EOF
+        
+        ytt -f prerelease.yaml -f overlay.yaml | kapp deploy -a kpack -y -f-
+
+        export IMAGE_REGISTRY=${{ env.REGISTRY_URL }}
+        export IMAGE_REGISTRY_USERNAME=${{ env.REGISTRY_USER }}
+        export IMAGE_REGISTRY_PASSWORD=${{ env.REGISTRY_PASS }}
+        export KPACK_TEST_NAMESPACE_LABELS="istio-injection=enabled"
+
+        make e2e
+
+  release:
+    needs:
+      - unit
+      - e2e
+      - generate-pre-release-yaml
+      - push-images
+      - build-images-linux
+      - build-images-windows
+    if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version-file: 'go.mod'
+
+    - name: Setup crane
+      uses: imjasonh/setup-crane@v0.3
+
+    - name: Setup carvel
+      uses: carvel-dev/setup-action@v1
+      with:
+        token: ${{ secrets.RELEASE_TOKEN }}
+        only: ytt
+
+    - name: Download artifacts
+      uses: actions/download-artifact@v3
+
+    - name: Docker Login
+      uses: docker/login-action@v2.1.0
+      with:
+        registry: gcr.io
+        username: _json_key
+        password: ${{ secrets.GCR_PUBLIC_SA }}
+
+    - name: Parse branch name
+      run: |
+        echo "GITHUB_REF=${GITHUB_REF}"
+        [[ $GITHUB_REF =~ ^refs\/heads\/release\/(.*)$ ]] && version=${BASH_REMATCH[1]}
+        if [[ -z "${version}" ]]; then
+          echo "ERROR: kpack version not detected."
+          exit 1
+        fi
+        echo "KPACK_VERSION=${version}" >> $GITHUB_ENV
+
+    - name: Promote images
+      env:
+        gcr_token: ${{ secrets.GCR_PUBLIC_SA }}
+      run: |
+        mkdir final-image-refs
+        for image in image-refs/*; do
+          dev_image=$(cat $image)
+          digest=$(echo $dev_image| cut -d "@" -f 2)
+          
+          name=$(basename $image)
+          final_repo="${{ env.PUBLIC_IMAGE_REPO }}/${name}" 
+          
+          crane copy "$dev_image" "$final_repo"
+          
+          echo "${final_repo}@${digest}" > final-image-refs/$name
+        done
+
+    - name: Upload image refs
+      uses: actions/upload-artifact@v3
+      with:
+        name: final-image-refs
+        path: final-image-refs/*
+
+    - name: Generate release yaml
+      id: release_yaml
+      run: |
+        file="release-${{ env.KPACK_VERSION }}.yaml"
+        ytt -f config/ \
+          -v controller_image=$(cat final-image-refs/controller) \
+          -v webhook_image=$(cat final-image-refs/webhook) \
+          -v build_init_image=$(cat final-image-refs/build-init) \
+          -v build_init_windows_image=$(cat final-image-refs/build-init-windows) \
+          -v build_waiter_image=$(cat final-image-refs/build-waiter) \
+          -v rebase_image=$(cat final-image-refs/rebase) \
+          -v completion_image=$(cat final-image-refs/completion) \
+          -v completion_windows_image=$(cat final-image-refs/completion-windows) \
+          -v lifecycle_image=$(cat final-image-refs/lifecycle) \
+          -v version=${{ env.KPACK_VERSION }} > $file
+        echo "sha=$(shasum -a 256 $file)" >> $GITHUB_OUTPUT
+
+    - name: Upload Release
+      uses: actions/upload-artifact@v3
+      with:
+        name: release
+        path: release-${{ env.KPACK_VERSION }}.yaml
+
+    - name: Create Draft Release
+      uses: softprops/action-gh-release@v1
+      with:
+        name: kpack v${{ env.KPACK_VERSION }}
+        tag_name: v${{ env.KPACK_VERSION }}
+        target_commitish: ${{ github.sha }}
+        token: ${{ secrets.RELEASE_TOKEN }}
+        draft: true
+        prerelease: true
+        files: release-*.yaml
+        body: |
+          ## What's Changed
+
+          ## Bug Fixes
+
+          ## Bumped Dependencies
+
+          sha256 checksum:
+          ```
+          ${{ steps.release_yaml.outputs.sha }}
+          ```
+
+          **Full Changelog**:
